# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chartEverything' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chartEverything

  target 'chartEverything-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chartEverythingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chartEverything-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chartEverything-tvOS

  target 'chartEverything-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core'
